### ISSUE TITLE
v2, UI review

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#3174]
Archived

**Comment by Popoulosss** [comment]
- [ ] Change the value of color `neutral200` in dark mode to #1E2130
- [ ] Set the background color #1C1F2E to `neutral200`
- [ ] Change the value of color `neutral300` in dark mode to #282B3B
- [ ] Change the value of color `navigationBorder` in dark mode to #282B3B

**Comment by Popoulosss** [comment]
- [ ] When the input component in active status, keep the border color `neutral500`

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/f95a05c1-1ff9-4e2d-be9f-24e61a69aadd">

**Comment by Popoulosss** [comment]
- [ ] Fix the divider line color
   - [ ] Discussion
   - [ ] All referenda
   - [ ] All referenda -> Tracks

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/01ac9e0f-0a5c-47a9-9292-53e3b50fa191">

**Comment by Popoulosss** [comment]
- [ ] Fix text color to `textPrimary`

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/bd2f29ab-fef9-4339-8e1a-64e473ca81d8">

**Comment by Popoulosss** [comment]
- [ ] Fix the countdown UI

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=1908-65308&mode=design&t=V2Yiif79eNJZhEuQ-11)

Perview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/6995a280-9e14-4023-916e-cc9f0d958e11">

**Comment by Popoulosss** [comment]
- [ ] Fix font size to 14px
- [ ] Set font color to `textSecondary` by default, turn to `textPrimary` when hovering over it

[Figma link](https://www.figma.com/file/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2?type=design&node-id=1924-58055&mode=design&t=XBJjaLWUV6QMDhI6-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a87f94ac-1064-4583-9d24-a0b1a3d9e27e">

**Comment by Popoulosss** [comment]
- [ ] Fix the layout of detail page

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/a20ecfdd-7795-498f-a5c8-6d03cce58cbb">
