### ISSUE TITLE
Collectives milestone 2

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4288]
- [x] #4314 
- [x] #4318
- [x] As a fellowship member, I want to see a list of referenda that I didn't yet vote, so I don't have to search from the whole referenda list.
- [x] #4406 
- [x] #4319
  - [x] My rank.
  - [x] My fellowship lifecycle or timeline, when I'm inducted, when promoted/demoted, etc.
  - [x] My salary. 
  - [x] Salary payments history. 
  - [x] Statistics
    - [x] How much salary totally I have claimed. Salary payment history. 
    - [x] Promotion/Demotion/Retention times.
- [x] #4329
  - [x] How much money is spent for fellowship
  - [x] How many times promotion/demotion happened
  - [x] Members. Total, core, salary, active members, rank distribution.
- [x] #4320
  - [x] My demotion/promotion period is closed
  - [x] My promotion/retain related events
- [x] #4497
  - [x] Show basic status like balances and a link to the address on explorers.
  - [x] Show various spends/proposals, bind them with referenda.
- [x] Referenda
  - [x] Bind evidence info in a promote/retain referendum #4311
  - [x] Add proposal templates(Promotion, Retain, Remark) to help users creating a referendum. https://github.com/opensquare-network/subsquare/issues/4282#issuecomment-2224991632

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/57k3GYwPnhvCgckzh4ERtk/SubSquare-v2.0?node-id=19408-35642&t=0fWV9L8vtCAprMlO-11)

**Comment by bkchr** [comment]
One improvement I would also like to see is that a referenda from an evidence is opened, the referenda text etc already points to the evidence and the title is related to what the referenda is doing.
