### ISSUE TITLE
refactor connect wallet related components

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#4416]
## background

- https://x.com/Ashutoshsinggh/status/1813159268411142516
- https://docs.subwallet.app/main/integration/integration-instructions

## jobs

- [x] #4413
- [x] rename
	- [x] `CONNECT_POPUP_VIEWS.WEB3` -> `CONNECT_POPUP_VIEWS.SUBSTRATE` #4439 
	- [x] rename file `polkadotWallet` to `SubstrateWallet`(common) #4439 
- [x] standalone wallet option
	- [x] mimir #4436 
- [x] `WalletOption`, refactor code structure #4451
- [x] `wallet/selectWallet.js`
- [x] `login/walletAddressSelect.js`
- [x] `connect/index.js`
- [x] extract `getSingleSigWallets, ...` to a hook:`useSubstrateWallets`
- [x] split ui logic to standalone
	- [x] substrate popup
	- [x] evm popup
	- [x] account(web2) popup
- [ ] hardware wallets?

## other related issues

- #4399 
	- #4400
