### ISSUE TITLE
Improve treasury spends asset meta parsing

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/subsquare#4693]
- [x] Show V4 spend asset token in overview recent spends list
- [x] Show V4 spend token in treasury spends list
- [x] Show V4 spend token in treasury spend detail sidebar
- [x] Fix Native token and DED token not display correctly
