### ISSUE TITLE
Enhance bounty features

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare#4812]
- [x] Enable curator creating child bounties. #4781
- [x] Enable propose curators for child bounties.  #4782 
- [x] Support accepting curator. 
   -  #4784 
   - #4783
- [x] Create a hint info to show do multisig actions with mimir #4824 
- [x] Support proposing curator on bounty detail page. This will create a referendum.

Other ideas:
- Statistics for parent bounties, like child bounty beneficiaries and payment distribution.
- Propose curator on bounty detail page which will create a referendum.
